name: CI-CD #nome do workflow
on:
  push:
    branches: ["main"] #todo push commit na main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest #define linux como runner
    steps:
      - name: Checkout #essa action traz todo o código pra dentro do runner, ele n fica disponível por padrão
        uses: actions/checkout@v4.1.7 #usa outra action criada em outro repositório

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            guilhermesilveiradev/review-filmes:v${{ github.run_number }}
            guilhermesilveiradev/review-filmes:latest
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI] #faz com que o job só seja executado após o primeiro
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      #configurar credenciais da aws
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: KubeConfig configure
        run: aws eks update-kubeconfig --name nomecluster

      - name: Deploy to kubernetes
        uses: Azure/k8s-deploy@v5.0.0
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            guilhermesilveiradev/review-filmes:v${{ github.run_number }}